version: "3.6"
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.0.2
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: admin_secret
  backend:
    build: 
      dockerfile: Dockerfile.dev
      context: ./backend
    command: npm run dev
    ports:
      - "4000:4000"
    volumes:
      - /usr/src/app/node_modules
      - ./backend:/usr/src/app
  frontend:
    build: 
      dockerfile: Dockerfile.dev
      context: ./frontend
    command: npm run start
    ports:
      - "3000:3000"
    volumes:
      - /usr/src/app/node_modules
      - ./frontend:/usr/src/app
volumes:
  db_data: